# Generated by Django 5.0.3 on 2024-03-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.IntegerField(choices=[(0, 'Work'), (1, 'Blog')], default=0, max_length=10),
        ),
    ]
