# Generated by Django 5.0.3 on 2024-03-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='description',
        ),
        migrations.AlterField(
            model_name='tech',
            name='type',
            field=models.IntegerField(choices=[(0, 'Learning'), (0, '+1 year'), (0, '+2 years'), (0, '+3 years')], default=0),
        ),
    ]
