# Generated by Django 5.0.3 on 2024-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tech_description_alter_tech_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='techs/'),
        ),
    ]
