# Generated by Django 5.0.3 on 2024-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tech_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tech',
            name='type',
            field=models.IntegerField(choices=[(0, 'Learning'), (1, '+1 year'), (2, '+2 years'), (3, '+3 years')], default=0),
        ),
    ]
